[package]
name = "dcm"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared-kernel = { path = "../shared-kernel" }
contracts = { path = "../contracts" }

bootstrap = { path = "../bootstrap" }
api = { path = "../api" }

tokio = { workspace = true }