[package]
name = "dcm"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared-kernel = { path = "../shared-kernel" }
contracts = { path = "../contracts" }
bootstrap = { path = "../bootstrap" }
api = { path = "../api" }
storage = { path = "../storage" }
dai = { path = "../core/dai" }

accounting = { path = "../modules/accounting" }
firewall = { path = "../modules/firewall" }

tokio = { workspace = true }

sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "migrate", "json", "chrono", "uuid"] }