[package]
name = "network"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
contracts = { path = "../../contracts" }
storage = { path = "../../storage" }

thiserror = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }