[package]
name = "api"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared-kernel = { path = "../shared-kernel" }
contracts = { path = "../contracts" }
storage = { path = "../storage" }

firewall = { path = "../modules/firewall" }
routing = { path = "../modules/routing" }
accounting = { path = "../modules/accounting" }

tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tower-http = { version = "0.5", features = ["cors"] }
rand = "0.8"